### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by Aaronius** [elcarim5efil/rollup-plugin-require-context#1]
Thanks for making this plugin. I tried to use it and when running tests I get the following:

```
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at getArgs (/Users/aahardy/dev/a-tag/node_modules/rollup-plugin-require-context/src/generate_require_context_code.js:14:21)
    at gernerateRequireContextCode (/Users/aahardy/dev/a-tag/node_modules/rollup-plugin-require-context/src/generate_require_context_code.js:40:16)
    at arr.map (/Users/aahardy/dev/a-tag/node_modules/rollup-plugin-require-context/src/index.js:22:16)
    at Array.map (<anonymous>:null:null)
    at Object.transform (/Users/aahardy/dev/a-tag/node_modules/rollup-plugin-require-context/src/index.js:21:11)
    at /Users/aahardy/dev/a-tag/node_modules/rollup/dist/rollup.js:16611:25
```

It looks like the problem stems from [this line](https://github.com/elcarim5efil/rollup-plugin-require-context/blob/master/src/generate_require_context_code.js#L13) which parses `args[1]`. `args[1]`, in my case, is `hash='3595a91798e6905ecea3ff7ba1047ee4e7823e8e'`.

I'm not really sure what's supposed to be happening here.

**Comment by ztamizzen** [comment]
I have the same issue. It looks like the string being parsed is badly formatted. It uses single quotes instead of double.

**Comment by elcarim5efil** [comment]
I've change the args extraction method which is [acorn](https://github.com/acornjs/acorn) the parse the AST. Problem should be solved. Please try updating to `@1.0.1`. Problem might be caused by the the RegExp parsing, just like @ztamizzen said.

Thank you for your reports and analysis. @Aaronius @ztamizzen
