### ISSUE TITLE
Cannot find module 'generate-source-map'

### ISSUE THREAD

**Issue by funyapu** [elcarim5efil/rollup-plugin-require-context#14]
Met bellow error with newest version; 1.0.1 and node v14.2.0.
Maybe forgot to add?

```
internal/modules/cjs/loader.js:1023
  throw err;
  ^
Error: Cannot find module 'generate-source-map'
Require stack:
- /path-to-dir/node_modules/rollup-plugin-require-context/src/index.js
- /path-to-dir/packages/vue/build/core.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path-to-dir/node_modules/rollup-plugin-require-context/src/index.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path-to-dir/node_modules/rollup-plugin-require-context/src/index.js',
    '/path-to-dir/packages/vue/build/core.js'
  ]
}
```

**Comment by funyapu** [comment]
I know I can just install it.
But  the package exact matches seems not well maintained and unpopular, I'm afraid it might be wrong one.
https://www.npmjs.com/package/generate-source-map

**Comment by tugberkgoc** [comment]
Just install the package, as you can see below

`npm install --save-dev generate-source-map@0.0.5`

Then, it will work as expected
